-- Armazena solicitações de cadastro sem depender de Auth/Edge Functions.
-- Fluxo público: INSERT anônimo em status "pending".

CREATE TABLE IF NOT EXISTS public.registrations (
  id bigint generated by default as identity primary key,
  name text NOT NULL,
  email text NOT NULL,
  account_type text NOT NULL CHECK (account_type IN ('user', 'company')),
  phone text NULL,
  company_name text NULL,
  cnpj text NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS registrations_email_pending_uniq
  ON public.registrations (lower(email))
  WHERE status = 'pending';

ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public insert registrations" ON public.registrations;
CREATE POLICY "public insert registrations"
  ON public.registrations
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (status = 'pending');
